#include"lists.h"
/**
 *dlistint_len-Returnsthenumberofelementsinalinkeddlistint_tlist.
 *@h:Apointertotheheadofthedoublylinkedlist.
 *Return:Thenumberofelementsinthelist.
 */
size_tdlistint_len(constdlistint_t*h)
{
    constdlistint_t*current=h;
    size_tcount=0;
    while(current!=NULL)
    {
        count++;
        current=current->next;
    }
    returncount;
}
